### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by CharoSW** [dozingcat/VectorCamera#13]
Assuming there is nothing particularly wrong with the concept is there a chance you could release this to F-Droid

**Comment by dozingcat** [comment]
I'd like to, I'll need to figure out how to build and package it for them.

**Comment by Poussinou** [comment]
I opened a Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/602).

To release this app, we need at least two things:
* Can you please tag your releases (see [here](https://help.github.com/articles/creating-releases/)), it would be helpful for future maintenance, since it allows automatic updates. You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)).
* Since F-Droid needs to build everything from source, we cannot keep [this jar](https://github.com/dozingcat/VectorCamera/blob/master/app/libs/vorbis-java-1.0.0-beta.jar). Could you please have a look at this, you can probably add it to gradle or something like that.

Thanks

**Comment by dozingcat** [comment]
Will the `libvpx.a` native libraries also be an issue? They're built from libvpx source files as described at https://github.com/dozingcat/WireGoggles/blob/master/README-libvpx.txt

**Comment by Rudloff** [comment]
We require everything to be built from source so if your build process uses prebuilt libraries, we will have to build them from source too. It's not impossible but will require a bit more work on our side.

**Comment by IzzySoft** [comment]
@dozingcat any news? [That request](https://gitlab.com/fdroid/rfp/issues/602) is still waiting.

**Comment by dozingcat** [comment]
Building the libvpx libraries from source is tricky and currently a manual process: https://github.com/dozingcat/VectorCamera/blob/master/README-libvpx.md. The best option may be to make a version without video encoding support.

**Comment by IzzySoft** [comment]
@Rudloff what'd you say, that sufficient?

@dozingcat if you could at least [tag](https://github.com/dozingcat/VectorCamera/releases) your releases and attach the APKs to the tags. I might be able to include your app [with my repo](https://apt.izzysoft.de/fdroid) for now (if it meets [my inclusion criteria](https://gitlab.com/IzzyOnDroid/repo) which I'm quite optimistic it will). Tags would be needed for F-Droid anyway :wink:

**Comment by Rudloff** [comment]
The instructions for building libvpx from source seem to be detailed enough so we can use them.
But `vorbis-java-1.0.0-beta.jar` is still a problem.

**Comment by dozingcat** [comment]
I've replaced the Vorbis jar file with the corresponding source, and created a tagged release at https://github.com/dozingcat/VectorCamera/releases/tag/v1.4.1.
